/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "on-secondary": "#ffffff",
              "on-error": "#ffffff",
              "surface-container-lowest": "#ffffff",
              "tertiary-fixed": "#a1f882",
              "primary-fixed-dim": "#ffb689",
              "on-tertiary-fixed-variant": "#115300",
              "secondary": "#5a5d73",
              "surface-tint": "#984800",
              "on-secondary-fixed": "#161b2d",
              "surface-container-high": "#e6e7f2",
              "on-secondary-container": "#5e6177",
              "surface-container": "#ecedf8",
              "on-error-container": "#93000a",
              "primary": "#984800",
              "on-tertiary-container": "#0c4200",
              "tertiary": "#1b6d01",
              "on-primary-fixed": "#311300",
              "surface": "#faf9ff",
              "on-secondary-fixed-variant": "#42465a",
              "on-primary-fixed-variant": "#733500",
              "secondary-fixed": "#dee1fa",
              "on-background": "#191b23",
              "surface-dark": "#171A29",
              "outline": "#8b7264",
              "on-primary": "#ffffff",
              "inverse-surface": "#2d3038",
              "inverse-on-surface": "#eff0fb",
              "primary-container": "#fc8019",
              "on-tertiary-fixed": "#032100",
              "status-error": "#E13D45",
              "surface-bright": "#faf9ff",
              "primary-fixed": "#ffdbc8",
              "on-surface": "#191b23",
              "error-container": "#ffdad6",
              "tertiary-fixed-dim": "#86db69",
              "surface-container-low": "#f2f3fe",
              "surface-dim": "#d8d9e4",
              "error": "#ba1a1a",
              "secondary-fixed-dim": "#c2c5de",
              "on-tertiary": "#ffffff",
              "status-success": "#60B246",
              "on-surface-variant": "#574236",
              "secondary-container": "#dbdef8",
              "tertiary-container": "#63b549",
              "surface-variant": "#e1e2ed",
              "outline-variant": "#dec1b0",
              "status-warning": "#DB7C38",
              "background": "#faf9ff",
              "surface-background": "#FFFFFF",
              "on-primary-container": "#5e2a00",
              "surface-container-highest": "#e1e2ed",
              "inverse-primary": "#ffb689"
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "spacing": {
              "section-gap": "32px",
              "gutter": "16px",
              "container-margin": "16px",
              "base": "8px",
              "card-padding": "12px"
          },
          "fontFamily": {
              "body-sm": ["Inter", "sans-serif"],
              "headline-xl": ["Inter", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "label-bold": ["Inter", "sans-serif"],
              "price-display": ["Inter", "sans-serif"],
              "headline-lg-mobile": ["Inter", "sans-serif"],
              "headline-md": ["Inter", "sans-serif"],
              "headline-lg": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"]
          },
          "fontSize": {
              "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
              "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
              "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
              "label-bold": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
              "price-display": ["16px", { "lineHeight": "20px", "fontWeight": "600" }],
              "headline-lg-mobile": ["20px", { "lineHeight": "28px", "fontWeight": "700" }],
              "headline-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
              "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
              "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
          }
      }
  },
  plugins: [],
}
