"""remove is_available from delivery_partner_profiles

Revision ID: 1b26bdab5165
Revises: 2143283a8b63
Create Date: 2026-05-27 12:03:43.284173
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b26bdab5165'
down_revision: Union[str, None] = '2143283a8b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_partner_profiles', 'is_available')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner_profiles', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
