"""add_delivery_domain

Revision ID: 2143283a8b63
Revises: d53fd07978c2
Create Date: 2026-05-27 10:53:46.186125
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2143283a8b63'
down_revision: Union[str, None] = 'd53fd07978c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_partner_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('vehicle_number', sa.String(length=30), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_deliveries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_partner_profiles_user_id'), 'delivery_partner_profiles', ['user_id'], unique=True)
    op.create_table('delivery_location_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('delivery_partner_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_partner_id'], ['delivery_partner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_location_logs_delivery_partner_id'), 'delivery_location_logs', ['delivery_partner_id'], unique=False)
    op.create_index(op.f('ix_delivery_location_logs_order_id'), 'delivery_location_logs', ['order_id'], unique=False)
    op.add_column('orders', sa.Column('assigned_delivery_partner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_orders_assigned_delivery_partner_id'), 'orders', ['assigned_delivery_partner_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'delivery_partner_profiles', ['assigned_delivery_partner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_assigned_delivery_partner_id'), table_name='orders')
    op.drop_column('orders', 'assigned_delivery_partner_id')
    op.drop_index(op.f('ix_delivery_location_logs_order_id'), table_name='delivery_location_logs')
    op.drop_index(op.f('ix_delivery_location_logs_delivery_partner_id'), table_name='delivery_location_logs')
    op.drop_table('delivery_location_logs')
    op.drop_index(op.f('ix_delivery_partner_profiles_user_id'), table_name='delivery_partner_profiles')
    op.drop_table('delivery_partner_profiles')
    # ### end Alembic commands ###
