"""Add composite indexes to Review model

Revision ID: 865e219e6a7a
Revises: cbb4656c8a0d
Create Date: 2026-05-27 15:49:55.236837
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865e219e6a7a'
down_revision: Union[str, None] = 'cbb4656c8a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reviews_customer_id_created_at', 'reviews', ['customer_id', 'created_at'], unique=False)
    op.create_index('ix_reviews_restaurant_id_created_at', 'reviews', ['restaurant_id', 'created_at'], unique=False)
    op.create_index('ix_reviews_restaurant_id_rating', 'reviews', ['restaurant_id', 'rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_restaurant_id_rating', table_name='reviews')
    op.drop_index('ix_reviews_restaurant_id_created_at', table_name='reviews')
    op.drop_index('ix_reviews_customer_id_created_at', table_name='reviews')
    # ### end Alembic commands ###
