"""delivery flow and earnings

Revision ID: b571ffda99e0
Revises: d0052118a538
Create Date: 2026-05-27 12:30:44.425821
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b571ffda99e0'
down_revision: Union[str, None] = 'd0052118a538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_partner_profiles', 'total_earnings',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.add_column('orders', sa.Column('earning_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('orders', sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('orders', 'delivery_earning',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'delivery_earning',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=False)
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'picked_up_at')
    op.drop_column('orders', 'earning_status')
    op.alter_column('delivery_partner_profiles', 'total_earnings',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=False)
    # ### end Alembic commands ###
