"""add delivery earning and accept time

Revision ID: d0052118a538
Revises: 1b26bdab5165
Create Date: 2026-05-27 12:22:31.688327
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0052118a538'
down_revision: Union[str, None] = '1b26bdab5165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner_profiles', sa.Column('total_earnings', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('delivery_earning', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('rider_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_user_roles', 'user_roles', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_roles', 'user_roles', type_='unique')
    op.drop_column('orders', 'rider_accepted_at')
    op.drop_column('orders', 'delivery_earning')
    op.drop_column('delivery_partner_profiles', 'total_earnings')
    # ### end Alembic commands ###
