"""update_document_type_enum

Revision ID: efdcd12e6a99
Revises: 24eece6fd5ec
Create Date: 2026-05-25 12:58:44.166833
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efdcd12e6a99'
down_revision: Union[str, None] = '24eece6fd5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    
    # Handle ENUM replacement for document_type_enum
    op.execute("TRUNCATE TABLE restaurant_documents CASCADE")
    op.execute("ALTER TYPE document_type_enum RENAME TO document_type_enum_old")
    op.execute("CREATE TYPE document_type_enum AS ENUM('FSSAI', 'GST', 'PAN', 'BANK_PROOF', 'OWNER_ID')")
    op.execute("ALTER TABLE restaurant_documents ALTER COLUMN document_type TYPE document_type_enum USING document_type::text::document_type_enum")
    op.execute("DROP TYPE document_type_enum_old")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE restaurant_documents CASCADE")
    op.execute("ALTER TYPE document_type_enum RENAME TO document_type_enum_new")
    op.execute("CREATE TYPE document_type_enum AS ENUM('FSSAI_LICENSE', 'TAX_ID', 'OWNER_ID', 'OTHER')")
    op.execute("ALTER TABLE restaurant_documents ALTER COLUMN document_type TYPE document_type_enum USING document_type::text::document_type_enum")
    op.execute("DROP TYPE document_type_enum_new")

    # ### end Alembic commands ###

