from enum import StrEnum

class AuditAction(StrEnum):
    USER_REGISTERED = "USER_REGISTERED"
    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"
    USER_PASSWORD_CHANGED = "USER_PASSWORD_CHANGED"
    USER_EMAIL_VERIFIED = "USER_EMAIL_VERIFIED"
    USER_SUSPENDED = "USER_SUSPENDED"
    USER_UNSUSPENDED = "USER_UNSUSPENDED"
    RESTAURANT_APPROVED = "RESTAURANT_APPROVED"
    RESTAURANT_REJECTED = "RESTAURANT_REJECTED"
    RESTAURANT_SUSPENDED = "RESTAURANT_SUSPENDED"
    ORDER_REFUNDED = "ORDER_REFUNDED"
    COUPON_CREATED = "COUPON_CREATED"
    COUPON_DELETED = "COUPON_DELETED"
    DELIVERY_PARTNER_APPROVED = "DELIVERY_PARTNER_APPROVED"
